### ISSUE TITLE
Are you using sparse graphs for MNIST?

### ISSUE THREAD

**Issue by chaitjo** [bknyaz/graph_attention_pool#2]
Hi @bknyaz, thanks for the well-documented codebase and new graph datasets!

I wanted to confirm: are the GNN models for the MNIST dataset operating on the fully-connected graph or a k-Nearest Neighbor graph (as in the MoNet and ChebNet papers, which use k = 8)? 

To me, it seems the code is using dense graphs for now.

**Comment by bknyaz** [comment]
Hi @chaitjo,

That's right, I use dense graphs in this work. Using sparse graphs has more sense in practice. I studied the difference between sparse and dense graphs in my another paper on "Image Classification with Hierarchical Multigraph Networks", see (Fig 6, c) there.

**Comment by chaitjo** [comment]
Thanks for the prompt reply and the useful paper!
